version: '3'

services: 

  nginx:
    image: nginx
    links:
      - jenkins
      - gitlab
    volumes: 
      # - ./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
      - ./nginx/gitlab.conf:/etc/nginx/conf.d/gitlab.conf
    ports:
     - 80:80


  jenkins:
    container_name: jenkins
    image: jenkins
    build: 
      dockerfile: jenkins/Dockerfile
      context: .
    ports: 
      - 50000:50000
      - 8080:8080
    links: 
      - gitlab
    volumes: 
     - jenkins_data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
     - jenkins_temp:/results

  gitlab:
    image: gitlab/gitlab-ce
    volumes: 
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    restart: always

volumes: 
  jenkins_data:
  jenkins_temp: